#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-terminado
Version  : 0.12.1
Release  : 51
URL      : https://files.pythonhosted.org/packages/7a/82/97a3b275b44b031eba1e27e136993464e670821aa4616a9dfaba0c2b4e8f/terminado-0.12.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/7a/82/97a3b275b44b031eba1e27e136993464e670821aa4616a9dfaba0c2b4e8f/terminado-0.12.1.tar.gz
Summary  : Tornado websocket backend for the Xterm.js Javascript terminal emulator library.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pypi-terminado-license = %{version}-%{release}
Requires: pypi-terminado-python = %{version}-%{release}
Requires: pypi-terminado-python3 = %{version}-%{release}
Requires: tornado
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(tornado)
BuildRequires : pypi(wheel)
BuildRequires : tornado

%description
This is a `Tornado <http://tornadoweb.org/>`_ websocket backend for the
`Xterm.js <https://xtermjs.org/>`_ Javascript terminal emulator
library.

%package license
Summary: license components for the pypi-terminado package.
Group: Default

%description license
license components for the pypi-terminado package.


%package python
Summary: python components for the pypi-terminado package.
Group: Default
Requires: pypi-terminado-python3 = %{version}-%{release}

%description python
python components for the pypi-terminado package.


%package python3
Summary: python3 components for the pypi-terminado package.
Group: Default
Requires: python3-core
Provides: pypi(terminado)
Requires: pypi(ptyprocess)
Requires: pypi(tornado)

%description python3
python3 components for the pypi-terminado package.


%prep
%setup -q -n terminado-0.12.1
cd %{_builddir}/terminado-0.12.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641512810
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-terminado
cp %{_builddir}/terminado-0.12.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-terminado/c469161e7fddd1ac349b03fa2732d18e96c579d2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-terminado/c469161e7fddd1ac349b03fa2732d18e96c579d2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
